### ISSUE TITLE
转换出的链接无法下载

### ISSUE THREAD

**Issue by NobodyHere-rrr** [acl4ssr-sub/acl4ssr-sub.github.io#3]
如题，下载时会提示http错误(400)
<img width="170" alt="截屏2021-01-09 12 57 21" src="https://user-images.githubusercontent.com/62543054/104083514-37c3d200-527a-11eb-96a8-3ce850b9c068.png">
<img width="425" alt="截屏2021-01-09 12 58 06" src="https://user-images.githubusercontent.com/62543054/104083519-51fdb000-527a-11eb-877e-0bd648105148.png">
<img width="476" alt="截屏2021-01-09 12 58 28" src="https://user-images.githubusercontent.com/62543054/104083523-5f1a9f00-527a-11eb-98dd-8db66837145f.png">

**Comment by NobodyHere-rrr** [comment]
额，没人回复那我就关issues了

**Comment by naiximcn** [comment]
额 这是api问题 这个api确实用不了 建议sub.xeton.dev那个 用了很久了 都可以用

**Comment by NobodyHere-rrr** [comment]
> 额 这是api问题 这个api确实用不了 建议sub.xeton.dev那个 用了很久了 都可以用

哪时我刚开始接触clash，没什么经验，才发了这个愚蠢至极的issue…
